#!/usr/bin/env python3
'''
procdockerstatsd
Daemon which periodically gathers process and docker statistics and pushes the data to STATE_DB
'''

import os
import psutil
import re
import subprocess
import sys
import time
from datetime import datetime, timedelta

from sonic_py_common import daemon_base
from swsscommon import swsscommon
from sonic_py_common.general import getstatusoutput_noshell_pipe, getstatusoutput_noshell

VERSION = '1.0'

SYSLOG_IDENTIFIER = "procdockerstatsd"

REDIS_HOSTIP = "127.0.0.1"

STAT_INTERVAL_S = 2 * 60
MEM_INTERVAL_S = 10 * 60
TIMEOUT_INTERVAL = 120


class ProcDockerStats(daemon_base.DaemonBase):
    all_process_obj = {}

    def __init__(self, log_identifier):
        super(ProcDockerStats, self).__init__(log_identifier)
        self.state_db = swsscommon.SonicV2Connector(host=REDIS_HOSTIP)
        self.state_db.connect("STATE_DB")
        self._mount_points_log_count = 10
        self._memory_stats_log_count = 10
        self._stats_update_log_count = 10

    def run_command(self, cmd, timeout=None):
        proc = subprocess.Popen(cmd, universal_newlines=True, stdout=subprocess.PIPE)
        if timeout is not None:
            try:
                (stdout, stderr) = proc.communicate(timeout=timeout)
                if proc.returncode != 0:
                    self.log_error("Error running command '{}'".format(cmd))
                    return None
                return stdout
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.communicate()
                self.log_error("Command '{}' timed out after {} seconds".format(cmd, timeout))
                return None
        else:
            (stdout, stderr) = proc.communicate()
            if proc.returncode != 0:
                self.log_error("Error running command '{}'".format(cmd))
                return None
            return stdout

    def format_docker_cmd_output(self, cmdout):
        lines = cmdout.splitlines()
        keys = re.split("   +", lines[0])
        docker_data = dict()
        docker_data_list = []
        for line in lines[1:]:
            values = re.split("   +", line)
            docker_data = {key: value for key, value in zip(keys, values)}
            docker_data_list.append(docker_data)
        formatted_dict = self.create_docker_dict(docker_data_list)
        return formatted_dict

    def format_process_cmd_output(self, cmdout):
        lines = cmdout.splitlines()
        keys = re.split(" +", lines[0])
        key_list = [key for key in keys if key]
        process_data = dict()
        process_data_list = []
        for line in lines[1:]:
            values = re.split(" +", line)
            # To remove extra space before UID
            val_list = [val for val in values if val]
            # Merging extra columns created due to space in cmd ouput
            val_list[8:] = [' '.join(val_list[8:])]
            process_data = {key: value for key, value in zip(key_list, val_list)}
            process_data_list.append(process_data)
        return process_data_list

    def format_mount_cmd_output(self, cmdout):
        formatted_dict = {}
        lines = cmdout.splitlines()
        mount_data_list = []
        for line in lines[1:]:
            values = line.split()
            mount_data_list.append(values)
        formatted_dict = self.create_mount_dict(mount_data_list)
        return formatted_dict

    def format_mem_output(self, data):
        formatted_dict = {}
        lines = data.splitlines()
        mem_map = {}
        for line in lines:
            key, value = line.split(":")
            mem_map[key] = value.strip().split()[0]
        formatted_dict = self.create_mem_dict(mem_map)
        return formatted_dict 

    def convert_to_bytes(self, value):
        UNITS_B = 'B'
        UNITS_KB = 'KB'
        UNITS_MB = 'MB'
        UNITS_MiB = 'MiB'
        UNITS_GiB = 'GiB'

        res = re.match(r'(\d+\.?\d*)([a-zA-Z]+)', value)
        value = float(res.groups()[0])
        units = res.groups()[1]
        if units.lower() == UNITS_KB.lower():
            value *= 1000
        elif units.lower() == UNITS_MB.lower():
            value *= (1000 * 1000)
        elif units.lower() == UNITS_MiB.lower():
            value *= (1024 * 1024)
        elif units.lower() == UNITS_GiB.lower():
            value *= (1024 * 1024 * 1024)

        return int(round(value))

    def create_docker_dict(self, dict_list):
        dockerdict = {}
        for row in dict_list[0:]:
            cid = row.get('CONTAINER ID')
            if cid:
                key = 'DOCKER_STATS|{}'.format(cid)
                dockerdict[key] = {}
                dockerdict[key]['NAME'] = row.get('NAME')

                cpu = row.get('CPU %').split("%")
                dockerdict[key]['CPU%'] = str(cpu[0])

                memuse = row.get('MEM USAGE / LIMIT').split(" / ")
                # converting MiB and GiB to bytes
                dockerdict[key]['MEM_BYTES'] = str(self.convert_to_bytes(memuse[0]))
                dockerdict[key]['MEM_LIMIT_BYTES'] = str(self.convert_to_bytes(memuse[1]))

                mem = row.get('MEM %').split("%")
                dockerdict[key]['MEM%'] = str(mem[0])

                netio = row.get('NET I/O').split(" / ")
                dockerdict[key]['NET_IN_BYTES'] = str(self.convert_to_bytes(netio[0]))
                dockerdict[key]['NET_OUT_BYTES'] = str(self.convert_to_bytes(netio[1]))

                blockio = row.get('BLOCK I/O').split(" / ")
                dockerdict[key]['BLOCK_IN_BYTES'] = str(self.convert_to_bytes(blockio[0]))
                dockerdict[key]['BLOCK_OUT_BYTES'] = str(self.convert_to_bytes(blockio[1]))

                dockerdict[key]['PIDS'] = row.get('PIDS')
        return dockerdict

    def _get_readonly_map(self):
        """Parse /proc/mounts and return {mount_path: 'true'/'false'}.

        The first comma-separated option in column 4 is always 'ro' or 'rw'.
        """
        readonly_map = {}
        try:
            with open('/proc/mounts', 'r') as f:
                for line in f:
                    parts = line.split()
                    if len(parts) >= 4:
                        mount_path = parts[1]
                        first_opt = parts[3].split(',')[0]
                        readonly_map[mount_path] = 'true' if first_opt == 'ro' else 'false'
        except OSError as e:
            self.log_warning("Failed to read /proc/mounts: {}".format(e))
        return readonly_map

    def create_mount_dict(self, dict_list):
        """Build MOUNT_POINTS dict from df --output rows.

        Expected column order (indices):
          0:source  1:fstype  2:size  3:used  4:avail  5:itotal  6:iavail  7:target

        InodeTotal and InodeAvailable come directly from df --output columns 5 and 6.
        ReadOnly is sourced from /proc/mounts (mount options column).
        """
        mountdict = {}
        readonly_map = self._get_readonly_map()

        for row in dict_list[0:]:
            if row[1] == "tmpfs" or row[1] == "devtmpfs" or row[1] == "overlay":
                continue
            mount_path = row[7]
            key = 'MOUNT_POINTS|{}'.format(mount_path)
            mountdict[key] = {}
            mountdict[key]['Filesystem'] = row[0]
            mountdict[key]['Type'] = row[1]
            mountdict[key]['1K-blocks'] = row[2]
            mountdict[key]['Used'] = row[3]
            mountdict[key]['Available'] = row[4]
            mountdict[key]['InodeTotal'] = row[5]
            mountdict[key]['InodeAvailable'] = row[6]
            mountdict[key]['ReadOnly'] = readonly_map.get(mount_path, 'false')
        return mountdict

    def create_mem_dict(self, mem_info):
        mem_dict = {}

        key = 'MEMORY_STATS|Physical'
        mem_dict[key] = {}
        mem_dict[key]['1K-blocks'] = str(mem_info["MemTotal"])
        mem_dict[key]['Used'] = str(int(mem_info["MemTotal"]) - int(mem_info["MemFree"]))

        key = 'MEMORY_STATS|Virtual'
        mem_dict[key] = {}
        mem_dict[key]['1K-blocks'] = str(int(mem_info["MemTotal"]) + int(mem_info["SwapTotal"]))
        mem_dict[key]['Used'] = str(int(mem_info["MemTotal"]) + int(mem_info["SwapTotal"]) - int(mem_info["MemFree"]) - int(mem_info["SwapFree"]))

        key = 'MEMORY_STATS|Buffer'
        mem_dict[key] = {}
        mem_dict[key]['1K-blocks'] = str(mem_info["MemTotal"])
        mem_dict[key]['Used'] = str(mem_info["Buffers"])

        key = 'MEMORY_STATS|Cached'
        mem_dict[key] = {}
        mem_dict[key]['1K-blocks'] = str(mem_info["Cached"])
        mem_dict[key]['Used'] = str(mem_info["Cached"])

        key = 'MEMORY_STATS|Shared'
        mem_dict[key] = {}
        mem_dict[key]['1K-blocks'] = str(mem_info["Shmem"])
        mem_dict[key]['Used'] = str(mem_info["Shmem"])

        key = 'MEMORY_STATS|Swap'
        mem_dict[key] = {}
        mem_dict[key]['1K-blocks'] = str(mem_info["SwapTotal"])
        mem_dict[key]['Used'] = str(int(mem_info["SwapTotal"]) - int(mem_info["SwapFree"]))

        return mem_dict

    def update_dockerstats_command(self):
        cmd = ["docker", "stats", "--no-stream", "-a"]
        data = self.run_command(cmd)
        if not data:
            self.log_error("'{}' returned null output".format(cmd))
            return False
        dockerdata = self.format_docker_cmd_output(data)
        if not dockerdata:
            self.log_error("formatting for docker output failed")
            return False
        # wipe out all data from state_db before updating
        self.state_db.delete_all_by_pattern('STATE_DB', 'DOCKER_STATS|*')
        for k1,v1 in dockerdata.items():
            self.batch_update_state_db(k1, v1)
        return True

    def update_processstats_command(self):
        processdata = []
        pid_set = set()

        processes_all = []
        for process_obj in psutil.process_iter(['pid', 'ppid', 'memory_percent', 'cpu_percent', 'create_time', 'cmdline']):
            processes_all.append(process_obj)
        valid_processes = []
        for p in processes_all:
            try:
                cpu = p.cpu_percent()
                valid_processes.append((cpu, p))
            except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
                continue
        sorted_processes = [p for _, p in sorted(valid_processes, key=lambda x: x[0], reverse=True)]
        top_processes = sorted_processes[:1024]
        for process_obj in top_processes:
            try:
                pid = process_obj.pid
                pid_set.add(pid)
                # store process object and reuse for CPU utilization
                if pid in self.all_process_obj:
                    process = self.all_process_obj[pid]
                else:
                    self.all_process_obj[pid] = process_obj
                    process = process_obj
                uid = process.uids()[0]
                ppid = process.ppid()
                mem = process.memory_percent()
                cpu = process.cpu_percent()
                stime = process.create_time()
                stime_formatted = datetime.utcfromtimestamp(stime).strftime("%b%d")
                tty = process.terminal()
                ttime = process.cpu_times()
                time_formatted = str(timedelta(seconds=int(ttime.user + ttime.system)))
                cmd = ' '.join(process.cmdline())

                row = {'PID': pid, 'UID': uid, 'PPID': ppid, '%CPU': cpu, '%MEM': mem, 'STIME': stime_formatted,  'TT': tty, 'TIME': time_formatted, 'CMD': cmd}
                processdata.append(row)
            except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
                pass

        # erase dead process
        remove_keys = []
        for id in self.all_process_obj:
            if id not in pid_set:
                remove_keys.append(id)
        for id in remove_keys:
            del self.all_process_obj[id]

        # wipe out all data before updating with new values
        self.state_db.delete_all_by_pattern('STATE_DB', 'PROCESS_STATS|*')

        update_value = {}
        for row in processdata:
            cid = row.get('PID')
            if cid:
                value = 'PROCESS_STATS|{}'.format(cid)
                uid = row.get('UID')
                update_value['UID'] = str(uid)
                ppid = row.get('PPID')
                update_value['PPID'] = str(ppid)
                cpu = row.get('%CPU')
                update_value['%CPU'] = str(cpu)
                mem = round(row.get('%MEM'), 1)
                update_value['%MEM'] = str(mem)
                stime = row.get('STIME')
                update_value['STIME'] = str(stime)
                tty = row.get('TT')
                update_value['TT'] = str(tty)
                time = row.get('TIME')
                update_value['TIME'] = str(time)
                cmd = row.get('CMD')
                update_value['CMD'] = cmd
                self.batch_update_state_db(value, update_value)

    def update_fipsstats_command(self):
        fips_db_key = 'FIPS_STATS|state'

        # Check if FIPS enforced in the current kernel cmdline
        with open('/proc/cmdline') as f:
           kernel_cmdline = f.read().strip().split(' ')
        enforced = 'sonic_fips=1' in kernel_cmdline or 'fips=1' in kernel_cmdline

        # Check if FIPS runtime status
        exitcode, _ = getstatusoutput_noshell_pipe(['sudo', 'openssl', 'engine', '-vv'], ['grep', '-i', 'symcryp'])
        enabled = not any(exitcode)
        update_value = {}
        update_value['timestamp'] = datetime.utcnow().isoformat()
        update_value['enforced'] = str(enforced)
        update_value['enabled'] = str(enabled)
        self.batch_update_state_db(fips_db_key, update_value)

    def update_mountpointstats_command(self):
        cmd = ["df", "--output=source,fstype,size,used,avail,itotal,iavail,target"]
        data = self.run_command(cmd)
        if not data:
            self.log_error("'{}' returned null output for filesystem".format(cmd))
            return False
        mountdata = self.format_mount_cmd_output(data)
        if not mountdata:
            self.log_error("formatting for filesystem output failed")
            return False
        self.state_db.delete_all_by_pattern('STATE_DB', 'MOUNT_POINTS|*')
        for k1, v1 in mountdata.items():
            self.batch_update_state_db(k1, v1)
        if self._mount_points_log_count > 0:
            self._mount_points_log_count -= 1
            self.log_info("MOUNT_POINTS updated. {} entries written".format(len(mountdata)))
        return True


    def update_memory_command(self):
        cmd = ["cat", "/proc/meminfo"]
        data = self.run_command(cmd)
        if not data:
            self.log_error("'{}' returned null output for memory stats".format(cmd))
            return False 
        memdata = self.format_mem_output(data)
        if not memdata:
            self.log_error("formatting for memory stats failed")
            return False 
        for k1, v1 in memdata.items():
            self.batch_update_state_db(k1, v1)
        if self._memory_stats_log_count > 0:
            self._memory_stats_log_count -= 1
            self.log_info("MEMORY_STATS updated. {} entries written".format(len(memdata)))
        return True

    def update_state_db(self, key1, key2, value2):
        self.state_db.set('STATE_DB', key1, key2, value2)

    def batch_update_state_db(self, key1, fvs):
        self.state_db.hmset('STATE_DB', key1, fvs)
  
    def run(self):
        self.log_info("Starting up ...")

        if not os.getuid() == 0:
            self.log_error("Must be root to run this daemon")
            print("Must be root to run this daemon")
            sys.exit(1)

        # MEM/MOUNT block runs once every (MEM_INTERVAL_S / STAT_INTERVAL_S) iterations.
        mem_ticks_per_run = MEM_INTERVAL_S // STAT_INTERVAL_S
        mem_counter = 0

        while True:
            datetimeobj = datetime.now()
            try:
                self.update_dockerstats_command()
                self.update_state_db('DOCKER_STATS|LastUpdateTime', 'lastupdate', str(datetimeobj))
            except Exception as e:
                self.log_error("Failed to update docker stats: {}".format(repr(e)))
            try:
                self.update_processstats_command()
                self.update_state_db('PROCESS_STATS|LastUpdateTime', 'lastupdate', str(datetimeobj))
            except Exception as e:
                self.log_error("Failed to update process stats: {}".format(repr(e)))
            try:
                self.update_fipsstats_command()
                self.update_state_db('FIPS_STATS|LastUpdateTime', 'lastupdate', str(datetimeobj))
            except Exception as e:
                self.log_error("Failed to update FIPS stats: {}".format(repr(e)))

            if mem_counter == 0:
                datetimeobj = datetime.now()
                try:
                    self.update_mountpointstats_command()
                    self.update_state_db('MOUNT_POINTS|LastUpdateTime', 'lastupdate', str(datetimeobj))
                except Exception as e:
                    self.log_error("Failed to update mount point stats: {}".format(repr(e)))
                try:
                    self.update_memory_command()
                except Exception as e:
                    self.log_error("Failed to update memory stats: {}".format(repr(e)))

                if self._stats_update_log_count > 0:
                    self._stats_update_log_count -= 1
                    stats_update_time = datetime.now()
                    self.log_info("All stats update finished at {}. Took {} seconds".format(stats_update_time, stats_update_time - datetimeobj))

            mem_counter = (mem_counter + 1) % mem_ticks_per_run

            # Data is refreshed every STAT_INTERVAL_S seconds (default 2 min).
            time.sleep(STAT_INTERVAL_S)

        self.log_info("Exiting ...")


def main():
    # Instantiate a ProcDockerStats object
    pd = ProcDockerStats(SYSLOG_IDENTIFIER)

    # Log all messages from INFO level and higher
    pd.set_min_log_priority_info()

    pd.run()


if __name__ == '__main__':
    main()

